### ISSUE TITLE
Allow usage of SoapHeader via steps

### ISSUE THREAD

**Issue by asgorobets** [asgorobets/SoapExtension#3]
We need to add support adding SoapHeader to the SoapRequest as some APIs require custom headers (sometimes for authentication).
http://php.net/manual/en/class.soapheader.php

Implement new step to add headers to the next request

**Comment by numerogeek** [comment]
Hi ! any updates planned on this ?

**Comment by asgorobets** [comment]
Hi @numerogeek, I can work on it this week if you need this feature, haven't started yet, but if you want to help contribute with a Pull Request that would also work for me and will be much appreciated. Let me know if you're interested

**Comment by numerogeek** [comment]
done @asgorobets

**Comment by asgorobets** [comment]
Merged, thanks @numerogeek for your contributions!
